version: 0.2
phases:
 pre_build:
   commands:
     - REPOSITORY_URI=671710932095.dkr.ecr.eu-south-1.amazonaws.com
     - echo $CODEBUILD_RESOLVED_SOURCE_VERSION      
     - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
     - IMAGE_TAG=${COMMIT_HASH}:latest
     - $(aws ecr get-login --no-include-email --region eu-south-1)
 install:
   runtime-versions:
     java: corretto11
 build:
   commands:
     - printf '{"ImageURI":"%s"}' $671710932095.dkr.ecr.eu-south-1.amazonaws.com:latest > imageDetail.json
     - docker build -t 671710932095.dkr.ecr.eu-south-1.amazonaws.com:latest .
     - docker push 671710932095.dkr.ecr.eu-south-1.amazonaws.com:latest
artifacts:
files: imageDetail.json
